### ISSUE TITLE
number of commads to limited

### ISSUE THREAD

**Issue by Kat-CeDe** [unfoldedcircle/integration-androidtv#27] opened 2024-02-24 08:51 UTC
### Description

To use this integration really a lot of commands are missing. These commands cannot be created in the integration only. Changes to ucapi media_player are needed.

### Additional context

Can you add the following commands to features of media_player?

	DIGIT_0 = "0"
	DIGIT_1 = "1"
	DIGIT_2 = "2"
	DIGIT_3 = "3"
	DIGIT_4 = "4"
	DIGIT_5 = "5"
	DIGIT_6 = "6"
	DIGIT_7 = "7"
	DIGIT_8 = "8"
	DIGIT_9 = "9"
	PAGE_UP = "page_up"
	PAGE_DOWN = "page_down"
	MOVE_HOME = "move_home"
	MOVE_END = "move_end"
	MEDIA_EJECT = "media_eject"
	MEDIA_RECORD = "media_record"
	INFO = "info"
	CHANNEL_UP = "channel_up"
	CHANNEL_DOWN = "channel_down"
	ZOOM_IN = "zoom_in"
	ZOOM_OUT = "zoom_out"
	TV = "tv"
	GUIDE = "guide"
	DVR = "dvr"
	BOOKMARK = "bookmarks"
	CAPTIONS = "captions"
	SETTINGS = "settings"
	TV_POWER = "tv_power"
	TV_INPUT = "tv_input"
	STB_POWER = "stb_power"
	STB_INPUT = "stb_input"
	AVR_POWER = "avr_power"
	AVR_INPUT = "avr_input"
	LANGUAGE_SWITCH = "language_switch"
	3D_MODE = "3d_mode"
	MUSIC = "music"
	BRIGHTNESS_DOWN = "brightness_down"
	BRIGHTNESS_UP = "brightness_up"
	MEDIA_AUDIO_TRACK = "media_audio_track"
	SLEEP = "sleep"
	WAKEUP = "wakeup"
	MEDIA_TOP_MENU = "media_top_menu"
	LAST_CHANNEL = "last_channel"
	TV_ZOOM_MODE = "tv_zoom_mode"
	TV_CONTENTS_MENU = "tv_contents_menu"
	TV_MEDIA_CONTEXT_MENU = "tv_media_context_menu"
	TV_TIMER_PROGRAMMING = "tv_timer_programming"

Thank you Ralf

**Comment by zehnm** [comment] 2024-02-26 09:56
Duplicate of https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/92

Supported commands depend on the integration API and related entity features.

The just released uc-api 0.9.0 supports more media-player features and a "simple command" option for all device commands not covered by a feature: https://github.com/unfoldedcircle/core-api/releases/tag/v0.9.0-beta

The following commands are now covered with the new features:
- DIGIT_0 .. 9 are suppored with the new `numpad` feature
- INFO: `info` feature
- GUIDE: `guide` feature
- MEDIA_EJECT: `eject` feature
- media_record, dvr, tv: `record` feature
- CAPTIONS: `subtitle` feature
- MEDIA_AUDIO_TRACK: `audio_track` feature

The remaining commands must be implemented with the new "simple command" option.

This will be supported in an upcoming firmware release. I'll keep this issue open until the firmware is released.

**Closed** 2024-03-28 17:03 UTC
Labels: enhancement
