### ISSUE TITLE
Holding a button

### ISSUE THREAD

**Issue by Lars-** [unfoldedcircle/integration-androidtv#23] opened 2024-01-08 13:11 UTC
### Description

Why isn't is possible to hold a button? For example: when I want to delete an item from my "Watch next" list, I need to hold the "OK"/"Enter" button for a few seconds. This doesn't seem possible with this integration, or am I wrong?

**Comment by zehnm** [comment] 2024-01-08 13:34
This is not yet possible at the moment where a long press in the remote UI translates to a long press in the integration. This integration only exposes a [media-player entity](https://github.com/unfoldedcircle/core-api/blob/main/doc/entities/entity_media_player.md) with the pre-defined commands.
One workaround would be to statically map this functionality to one of the media-player functions, so that it sends a long press to the Android device.

We are planning to enhance the media-player with "extra commands" or adding a generic "remote-entity" (if we can't come up with a better name to avoid confusion) where buttons / commands support long-presses.

**Comment by WillTriumph1** [comment] 2024-02-02 20:10
Please. When will long press be added?

**Comment by werpu** [comment] 2024-02-05 07:30
I would vote this up if it would be possible, this functionality is basically the last real showstopper in the Android TV integration and basically the last functionality which makes it subpar to the Harmony integration.
 The ok long press is used in various places on the Shield not only for the watch list, for instance, you use it to show the currently running tasks to be able to kill off a running app!

**Comment by zehnm** [comment] 2024-02-23 20:19
Duplicate of unfoldedcircle/feature-and-bug-tracker#90, unfoldedcircle/feature-and-bug-tracker#94
Also requires unfoldedcircle/core-api#32

**Closed by zehnm** 2024-02-23 20:19 UTC
Labels: enhancement
